BEGIN;

DROP TABLE IF EXISTS word;
DROP TABLE IF EXISTS pos;
DROP TABLE IF EXISTS word_pos;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS "class";
DROP TABLE IF EXISTS word_class;

COMMIT;
