PROJECT_NAME=admin-api
OUTPUT_DIRECTORY=./bin
BINARY=$OUTPUT_DIRECTORY/$PROJECT_NAME

DEPLOY_BRANCH=master
DEPLOY_DIRECTORY=/usr/local/spongeling/admin-api
DEPLOY_TARGET=$DEPLOY_DIRECTORY/$PROJECT_NAME
